name: release
on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v1.0.0

permissions:
  contents: write  # Required for creating and managing release assets

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3

      - 
        name: Check if tag is on main
        run: |
          DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
          TAG_COMMIT_BRANCH=$(git branch -r --contains $GITHUB_SHA | grep "origin/$DEFAULT_BRANCH" || true)
          if [[ -z "$TAG_COMMIT_BRANCH" ]]; then
            echo "Tag is not on main branch. Exiting."
            exit 1
          fi

      - 
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true

      - 
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - 
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --clean
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
